#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell available, run the
#       script as that shell. For example, as:
#
#        bash Gradle
#
#   (2) The Gradle binaries should be on the PATH environment variable when running this script.
#       If they are not, you can set the JAVA_HOME environment variable.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}	# leaves a trailing /; empty if no leading path
    [ -n "$APP_HOME" ] &&	# if APP_HOME is empty, we're done
    APP_HOME=$(cd "$APP_HOME" 2>/dev/null && pwd) || break
do
  app_path="${app_path%"${app_path##*/}"}../"; [ -n "$app_path" ]
done

# Fallback in case pwd failed
APP_HOME=${APP_HOME:-"$(cd "$(dirname "$0")/.." 2>/dev/null || echo "$PWD")" }

APP_NAME="Gradle"
APP_HOME_ESCAPED=$(printf '%s\n' "$APP_HOME" | sed 's/[^\/]/[&]/g')
CLASSPATH=$(printf '%s\n' "$APP_HOME_ESCAPED"/lib/* | tr '\n' ':')
CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar:$CLASSPATH"

# This is normally unused
export CLASSPATH="$CLASSPATH"

exec "$JAVA_HOME/bin/java" \
  ${JAVA_OPTS} \
  -Dorg.gradle.appname="$APP_NAME" \
  -Dorg.gradle.wrapper.properties="$APP_HOME/gradle/wrapper/gradle-wrapper.properties" \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
